#!/usr/bin/env python3
"""Check the Xcode development suffix validator directly or in generated PBX phases.

Default mode calls the shared validator without requiring XcodeGen. Use ``--generated`` to
generate the real Pincer project in a temporary directory and execute the shell build phases
that XcodeGen placed before each target's Compile Sources phase. ``--existing-project`` inspects
and executes those phases from a project generated by another process, such as the CI hook.
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import shutil
import subprocess
import tempfile
import unittest
from typing import Any


REPO = pathlib.Path(__file__).resolve().parents[1]
VALIDATOR = REPO / "scripts/validate-xcode-dev-suffix.sh"
TARGETS = (
    "Pincer-macOS",
    "Pincer-iOS",
    "PincerShare-macOS",
    "PincerShare-iOS",
    "PincerNotifications-iOS",
)
VALID_SUFFIXES = (
    "",
    ".dev-a",
    ".dev-7",
    ".dev-a1-b2",
    ".dev-feature-x",
    ".dev-" + "a" * 24,
)
INVALID_SUFFIXES = (
    "dev-feature-x",  # Missing the documented prefix.
    "dev-x",  # Missing the documented prefix.
    ".dev-",  # Empty namespace.
    ".dev-Upper",  # Uppercase is not canonical.
    ".dev-feature_x",  # Underscore is not canonical.
    ".dev-café",  # Namespace characters must be ASCII.
    ".dev-x.y",  # Dots are not namespace separators.
    ".dev-x/y",  # Slashes must be rejected before reaching shell paths.
    ".dev-x\n",  # Newlines must be rejected before reaching shell paths.
    ".dev--feature",  # Leading namespace hyphen.
    ".dev-feature-",  # Trailing namespace hyphen.
    ".dev-feature--x",  # Repeated separator.
    ".dev-" + "a" * 25,  # Namespace exceeds DevNamespace.maxLength.
)
MAX_DIAGNOSTIC_BYTES = 8 * 1024
MAX_PBX_JSON_BYTES = 32 * 1024 * 1024


def tail(path: pathlib.Path, limit: int = MAX_DIAGNOSTIC_BYTES) -> str:
    """Read only a bounded diagnostic tail from a subprocess output file."""
    size = path.stat().st_size
    with path.open("rb") as stream:
        stream.seek(max(0, size - limit))
        return stream.read(limit).decode("utf-8", errors="replace")


def run_bounded(
    command: list[str],
    *,
    cwd: pathlib.Path,
    env: dict[str, str],
    output_directory: pathlib.Path,
    timeout: float,
    label: str,
) -> tuple[int, str]:
    """Keep subprocess output file-backed and return only a bounded diagnostic tail."""
    stdout_path = output_directory / f"{label}.stdout"
    stderr_path = output_directory / f"{label}.stderr"
    with stdout_path.open("wb") as stdout, stderr_path.open("wb") as stderr:
        process = subprocess.Popen(command, cwd=cwd, env=env, stdout=stdout, stderr=stderr)
        try:
            return_code = process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            process.terminate()
            try:
                process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                process.kill()
                try:
                    process.wait(timeout=2)
                except subprocess.TimeoutExpired as error:
                    raise AssertionError(f"{label} exceeded {timeout:g}s and did not stop after kill") from error
            raise AssertionError(f"{label} exceeded {timeout:g}s: {tail(stderr_path)}")
    diagnostic = tail(stderr_path)
    if not diagnostic:
        diagnostic = tail(stdout_path)
    return return_code, diagnostic


def validator_environment(suffix: str) -> dict[str, str]:
    env = os.environ.copy()
    env["PINCER_DEV_SUFFIX"] = suffix
    env["SRCROOT"] = str(REPO)
    env["PROJECT_DIR"] = str(REPO)
    return env


def run_shared_validator(suffix: str, scratch: pathlib.Path, label: str) -> tuple[int, str]:
    if not VALIDATOR.is_file():
        return 127, f"shared validator is missing: {VALIDATOR}"
    return run_bounded(
        ["/bin/sh", str(VALIDATOR)],
        cwd=REPO,
        env=validator_environment(suffix),
        output_directory=scratch,
        timeout=5,
        label=label,
    )


class DirectValidatorTests(unittest.TestCase):
    def test_documented_and_canonical_suffixes_are_accepted(self) -> None:
        failures: list[str] = []
        with tempfile.TemporaryDirectory(prefix="pincer-suffix-direct-") as temporary:
            scratch = pathlib.Path(temporary)
            for index, suffix in enumerate(VALID_SUFFIXES):
                result, diagnostic = run_shared_validator(suffix, scratch, f"valid-{index}")
                if result != 0:
                    failures.append(f"{suffix!r}: exit {result}; {diagnostic}")
        self.assertEqual(failures, [], "valid suffixes were rejected: " + " | ".join(failures))

    def test_noncanonical_suffixes_are_rejected(self) -> None:
        failures: list[str] = []
        with tempfile.TemporaryDirectory(prefix="pincer-suffix-direct-") as temporary:
            scratch = pathlib.Path(temporary)
            for index, suffix in enumerate(INVALID_SUFFIXES):
                result, _ = run_shared_validator(suffix, scratch, f"invalid-{index}")
                if result == 0:
                    failures.append(repr(suffix))
        self.assertEqual(failures, [], "validator accepted malformed suffixes: " + ", ".join(failures))


class GeneratedProjectTests(unittest.TestCase):
    existing_project: pathlib.Path | None = None

    @classmethod
    def setUpClass(cls) -> None:
        plutil = shutil.which("plutil")
        if plutil is None:
            raise AssertionError("project inspection requires plutil")

        cls._temporary = tempfile.TemporaryDirectory(prefix="pincer-generated-suffix-")
        cls.addClassCleanup(cls._temporary.cleanup)
        cls.scratch = pathlib.Path(cls._temporary.name)
        if cls.existing_project is None:
            xcodegen = shutil.which("xcodegen")
            if xcodegen is None:
                raise AssertionError("--generated requires XcodeGen; it must not skip when unavailable")
            generated_directory = cls.scratch / "generated-project"
            generated_directory.mkdir()
            env = os.environ.copy()
            env.pop("PINCER_DEV_SUFFIX", None)
            env.pop("PINCER_APP_STORE_SIGNING", None)
            # CI's real generation runs the postGen hook, which invokes --existing-project. This
            # isolated --generated check owns its phase execution and must not recurse into it.
            env.pop("GITHUB_ACTIONS", None)
            result, diagnostic = run_bounded(
                [
                    xcodegen,
                    "--spec",
                    str(REPO / "project.yml"),
                    "--project",
                    str(generated_directory),
                    "--project-root",
                    str(REPO),
                    "--quiet",
                ],
                cwd=REPO,
                env=env,
                output_directory=cls.scratch,
                timeout=90,
                label="xcodegen",
            )
            if result != 0:
                raise AssertionError(f"XcodeGen failed with exit {result}: {diagnostic}")
            pbxproj = generated_directory / "Pincer.xcodeproj/project.pbxproj"
            if not pbxproj.is_file():
                raise AssertionError(f"XcodeGen did not create {pbxproj}")
        else:
            project_path = cls.existing_project.expanduser().resolve()
            if project_path.suffix == ".xcodeproj" and project_path.is_dir():
                pbxproj = project_path / "project.pbxproj"
            elif project_path.name == "project.pbxproj" and project_path.is_file():
                pbxproj = project_path
            else:
                raise AssertionError(
                    "--existing-project expects a .xcodeproj directory or its project.pbxproj file"
                )
            if not pbxproj.is_file():
                raise AssertionError(f"existing project is missing {pbxproj}")
            env = os.environ.copy()

        json_path = cls.scratch / "project.json"
        result, diagnostic = run_bounded(
            [plutil, "-convert", "json", "-o", str(json_path), str(pbxproj)],
            cwd=REPO,
            env=env,
            output_directory=cls.scratch,
            timeout=15,
            label="plutil",
        )
        if result != 0:
            raise AssertionError(f"plutil could not decode generated project (exit {result}): {diagnostic}")
        if json_path.stat().st_size > MAX_PBX_JSON_BYTES:
            raise AssertionError("generated PBX JSON exceeded the 32 MiB fixture limit")

        try:
            cls.project = json.loads(json_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise AssertionError(f"could not read generated PBX JSON: {error}") from error
        cls.objects: dict[str, dict[str, Any]] = cls.project.get("objects", {})
        cls.targets = cls.find_targets(cls.objects)

    @classmethod
    def tearDownClass(cls) -> None:
        if hasattr(cls, "_temporary"):
            cls._temporary.cleanup()

    @staticmethod
    def find_targets(objects: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
        found = {
            str(obj.get("name")): obj
            for obj in objects.values()
            if obj.get("isa") == "PBXNativeTarget" and obj.get("name") in TARGETS
        }
        missing = [name for name in TARGETS if name not in found]
        if missing:
            raise AssertionError("generated project is missing expected native targets: " + ", ".join(missing))
        return found

    def run_target_pre_source_phases(
        self, target_name: str, suffix: str, case_label: str
    ) -> tuple[int, str, int]:
        target = self.targets[target_name]
        phase_ids = target.get("buildPhases", [])
        phase_objects = [self.objects.get(identifier, {}) for identifier in phase_ids]
        source_index = next(
            (index for index, phase in enumerate(phase_objects) if phase.get("isa") == "PBXSourcesBuildPhase"),
            None,
        )
        self.assertIsNotNone(source_index, f"{target_name} has no PBXSourcesBuildPhase")
        script_phases = [
            phase
            for phase in phase_objects[:source_index]
            if phase.get("isa") == "PBXShellScriptBuildPhase"
        ]
        environment = validator_environment(suffix)
        environment.update(
            {
                "TARGET_NAME": target_name,
                "CONFIGURATION": "Debug",
                "ACTION": "build",
                "DERIVED_FILE_DIR": str(self.scratch / "derived" / target_name),
                "BUILT_PRODUCTS_DIR": str(self.scratch / "products" / target_name),
            }
        )
        pathlib.Path(environment["DERIVED_FILE_DIR"]).mkdir(parents=True, exist_ok=True)
        pathlib.Path(environment["BUILT_PRODUCTS_DIR"]).mkdir(parents=True, exist_ok=True)
        last_diagnostic = ""
        for index, phase in enumerate(script_phases):
            script = phase.get("shellScript")
            self.assertIsInstance(script, str, f"{target_name} pre-source shell phase has no script")
            shell = phase.get("shellPath") or "/bin/sh"
            script_path = self.scratch / f"{target_name}-{index}.sh"
            script_path.write_text(script, encoding="utf-8")
            return_code, last_diagnostic = run_bounded(
                [shell, str(script_path)],
                cwd=REPO,
                env=environment,
                output_directory=self.scratch,
                timeout=5,
                label=f"phase-{target_name}-{case_label}-{index}",
            )
            if return_code != 0:
                return return_code, last_diagnostic, len(script_phases)
        return 0, last_diagnostic, len(script_phases)

    def test_valid_suffixes_pass_the_generated_target_phases(self) -> None:
        failures: list[str] = []
        for target_name in TARGETS:
            for case_index, suffix in enumerate(VALID_SUFFIXES):
                result, diagnostic, _ = self.run_target_pre_source_phases(
                    target_name, suffix, f"valid-{case_index}"
                )
                if result != 0:
                    failures.append(f"{target_name} {suffix!r}: exit {result}; {diagnostic}")
        self.assertEqual(failures, [], "valid suffixes failed generated build phases: " + " | ".join(failures))

    def test_invalid_suffixes_fail_before_sources_for_every_target(self) -> None:
        accepted: list[str] = []
        unguarded: list[str] = []
        for target_name in TARGETS:
            for case_index, suffix in enumerate(INVALID_SUFFIXES):
                result, diagnostic, phase_count = self.run_target_pre_source_phases(
                    target_name, suffix, f"invalid-{case_index}"
                )
                if result == 0:
                    accepted.append(f"{target_name} {suffix!r}")
                    if phase_count == 0:
                        unguarded.append(target_name)
                else:
                    self.assertTrue(diagnostic, f"{target_name} {suffix!r} failed without a useful diagnostic")
        self.assertEqual(
            accepted,
            [],
            "generated target phases accepted malformed suffixes"
            + ("; targets without a pre-source guard: " + ", ".join(sorted(set(unguarded))) if unguarded else "")
            + (": " + " | ".join(accepted) if accepted else ""),
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--generated",
        action="store_true",
        help="require XcodeGen and execute actual generated pre-source shell phases",
    )
    mode.add_argument(
        "--direct",
        action="store_true",
        help="call the shared suffix validator directly without requiring XcodeGen",
    )
    mode.add_argument(
        "--existing-project",
        type=pathlib.Path,
        metavar="XCODEPROJ_OR_PBXPROJ",
        help="inspect and execute pre-source phases from an already-generated Xcode project",
    )
    args = parser.parse_args()
    if args.existing_project is not None:
        GeneratedProjectTests.existing_project = args.existing_project
        selected = GeneratedProjectTests
    elif args.generated:
        selected = GeneratedProjectTests
    else:
        selected = DirectValidatorTests
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(selected)
    return 0 if unittest.TextTestRunner(verbosity=2).run(suite).wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
