#if os(iOS)
import Foundation
import SwiftUI
import Testing
import UIKit
@testable import PincerKit
@testable import PincerUI

/// Measures UIKit's actual toolbar generated by ChatChrome; no substitute toolbar content.
@MainActor
private struct CompactChatChromeHost: View {
    let app: AppModel
    let gateway: GatewayStore
    let geometryProbe: CompactChatHeaderGeometryProbe

    var body: some View {
        NavigationStack {
            Text("Native chat chrome geometry")
                .modifier(ChatChrome())
        }
        .environment(self.app)
        .environment(self.gateway)
        .environment(\.compactChatHeaderGeometryProbe, self.geometryProbe)
        .defaultAppStorage(self.gateway.defaults)
        .environment(\.horizontalSizeClass, .compact)
    }
}

@MainActor
private struct CompactChatChromeToolbarTests {
    @MainActor
    private struct NativeHost {
        let controller: UIHostingController<CompactChatChromeHost>
        let window: UIWindow
        let previous: UIWindow?
        let geometry: CenteredHeaderGeometryRecorder

        init(app: AppModel, gateway: GatewayStore) {
            let geometry = CenteredHeaderGeometryRecorder()
            self.geometry = geometry
            let probe = CompactChatHeaderGeometryProbe { part, frame in geometry.frames[part] = frame }
            let controller = UIHostingController(rootView: CompactChatChromeHost(app: app, gateway: gateway, geometryProbe: probe))
            controller.overrideUserInterfaceStyle = .light
            let scene = UIApplication.shared.connectedScenes.compactMap { $0 as? UIWindowScene }
                .first { $0.activationState != .unattached }
            let window: UIWindow
            if let scene { window = UIWindow(windowScene: scene) }
            else { window = UIWindow(frame: CGRect(x: 0, y: 0, width: 390, height: 844)) }
            window.frame = CGRect(x: 0, y: 0, width: 390, height: 844)
            window.rootViewController = controller
            self.controller = controller
            self.window = window
            self.previous = scene?.windows.first(where: { $0.isKeyWindow })
            window.makeKeyAndVisible()
        }

        func close() { self.window.isHidden = true; self.previous?.makeKeyAndVisible() }
    }

    private struct Geometry {
        let itemCount: Int
        let itemWidths: [CGFloat]
        let navigationBarWidth: CGFloat
        let labels: [String]
        let blankReservedFrames: [CGRect]
        let visibleActionCount: Int
        let trailingGroupWidth: CGFloat
    }

    private func descendants(_ view: UIView) -> [UIView] {
        [view] + view.subviews.flatMap(self.descendants)
    }

    private func controllers(_ controller: UIViewController) -> [UIViewController] {
        [controller] + controller.children.flatMap(self.controllers)
    }

    private func navigationBars(in window: UIWindow, controller: UIViewController) -> [UINavigationBar] {
        var bars = self.descendants(window).compactMap { $0 as? UINavigationBar }
        for child in self.controllers(controller) {
            if let navigation = child as? UINavigationController,
               !bars.contains(where: { $0 === navigation.navigationBar }) { bars.append(navigation.navigationBar) }
        }
        return bars
    }

    private func diagnose(_ window: UIWindow, controller: UIViewController) {
        print("Compact ChatChrome window frame=\(window.frame) bounds=\(window.bounds) hidden=\(window.isHidden) scene=\(window.windowScene != nil)")
        for child in self.controllers(controller).prefix(40) {
            print("  controller \(String(describing: type(of: child))) loaded=\(child.isViewLoaded) frame=\(child.viewIfLoaded?.frame ?? .zero)")
        }
        for view in self.descendants(window).prefix(240) {
            print("  window view \(String(describing: type(of: view))) frame=\(view.convert(view.bounds, to: window)) hidden=\(view.isHidden) accessibility=\(view.accessibilityLabel ?? "nil")")
        }
        for bar in self.navigationBars(in: window, controller: controller) {
            print("  navbar frame=\(bar.frame) topTitle=\(bar.topItem?.title ?? "nil") rightItems=\(bar.topItem?.rightBarButtonItems?.count ?? -1) leftItems=\(bar.topItem?.leftBarButtonItems?.count ?? -1)")
        }
    }

    private func measure(_ app: AppModel, gateway: GatewayStore, key: String, existingHost: NativeHost? = nil) async throws -> Geometry {
        gateway.selectedKey = key
        let host = existingHost ?? NativeHost(app: app, gateway: gateway)
        let controller = host.controller, window = host.window
        defer { if case nil = existingHost { host.close() } }
        let ready = await eventually(timeout: .seconds(15)) {
            window.layoutIfNeeded()
            controller.view.layoutIfNeeded()
            return self.navigationBars(in: window, controller: controller)
                .contains { $0.bounds.width > 0 && $0.topItem != nil }
                && host.geometry.frames.count == 3 && host.geometry.frames.values.allSatisfy { $0.width > 0 && $0.height > 0 }
        }
        self.diagnose(window, controller: controller)
        try #require(ready, "actual NavigationStack must install its native compact navigation bar")
        let bar = try #require(self.navigationBars(in: window, controller: controller).first { $0.bounds.width > 0 && $0.topItem != nil })
        let rightItems = bar.topItem?.rightBarButtonItems ?? []
        let groupItems = bar.topItem?.trailingItemGroups.flatMap(\.barButtonItems) ?? []
        let items = rightItems.isEmpty ? groupItems : rightItems
        // SwiftUI's native bar can render its items without populating UINavigationItem's
        // legacy or grouped collections. In that case read the rendered per-item host frames,
        // not a product-state predicate or a replacement toolbar. Type names select views
        // already observed in the native hierarchy; no private API is called.
        let nativeItemFrames = self.descendants(bar).compactMap { view -> CGRect? in
            let name = String(describing: type(of: view))
            guard name.contains("UIKitBarItemHost") || name == "_UIButtonBarButton" else { return nil }
            let frame = view.convert(view.bounds, to: bar)
            return frame.maxX > bar.bounds.midX ? frame : nil
        }
        let publicFrames = items.compactMap { $0.customView }.map { $0.convert($0.bounds, to: bar) }
        let frames = items.isEmpty ? nativeItemFrames : publicFrames
        let blankFrames = frames.filter { $0.width > 1 && $0.height <= 1 }
        let visibleActions = nativeItemFrames.filter { $0.width > 1 && $0.height > 1 }.count
        let groupWidth = self.descendants(bar).filter {
            String(describing: type(of: $0)) == "UIPlatformGlassInteractionView"
                && $0.convert($0.bounds, to: bar).maxX > bar.bounds.midX
        }.map(\.bounds.width).max() ?? frames.reduce(CGRect.null) { $0.union($1) }.width
        let itemCount = items.isEmpty ? nativeItemFrames.count : items.count
        let labels = self.descendants(bar).compactMap(\.accessibilityLabel).filter { !$0.isEmpty }
        let widths = items.isEmpty ? frames.map(\.width) : items.map { $0.customView?.bounds.width ?? $0.width }
        print("Compact ChatChrome native key=\(key) branches=\(gateway.chat(for: key).branches.count) running=\(gateway.subagentTree(rootKey: key).runningCount) rightItems=\(rightItems.count) groupedItems=\(groupItems.count) renderedItems=\(nativeItemFrames.count) widths=\(widths) frames=\(frames) blankFrames=\(blankFrames) visibleActions=\(visibleActions) trailingGroupWidth=\(groupWidth) labels=\(labels) barWidth=\(bar.bounds.width)")
        for view in self.descendants(bar) where view.bounds.width > 0 {
            print("  native \(String(describing: type(of: view))) frame=\(view.convert(view.bounds, to: bar)) accessibility=\(view.accessibilityLabel ?? "nil")")
        }
        let image = UIGraphicsImageRenderer(bounds: bar.bounds).image { renderer in
            if !bar.drawHierarchy(in: bar.bounds, afterScreenUpdates: true) { bar.layer.render(in: renderer.cgContext) }
        }
        let path = FileManager.default.temporaryDirectory.appendingPathComponent("pincer-compact-chat-chrome-\(gateway.chat(for: key).branches.count)-branches-\(UUID().uuidString).png")
        try #require(image.pngData()).write(to: path)
        print("Compact ChatChrome native navigation bar snapshot: \(path.path)")
        #expect(bar.bounds.width == 390, "the production modifier is hosted at compact iPhone width")
        try #require(nativeItemFrames.count >= 1, "the measured native hierarchy must contain the actual Chat Options host")
        return Geometry(itemCount: itemCount, itemWidths: widths, navigationBarWidth: bar.bounds.width, labels: labels,
                        blankReservedFrames: blankFrames, visibleActionCount: visibleActions, trailingGroupWidth: groupWidth)
    }

    func actualCompactNavigationBarReservesOnlyVisibleChatActions() async throws {
        let scratch = ScratchDefaults()
        let app = AppModel(defaults: scratch.defaults)
        let gateway = app.add(.demo(), secret: nil)
        gateway.cacheRoot = nil
        gateway.notifier = nil
        defer { app.remove(gateway.id); scratch.remove() }
        let singleKey = "agent:main:dashboard:trip"
        let branchedKey = "agent:main:dashboard:garden"
        let runningKey = "agent:research:dashboard:launch-plan"
        let connected = await eventually(timeout: .seconds(30)) {
            gateway.state.isConnected && [singleKey, branchedKey, runningKey].allSatisfy { gateway.sessions[$0] != nil }
        }
        try #require(connected, "actual seeded Demo chats must be connected before measuring native chrome")
        for key in [singleKey, branchedKey, runningKey] {
            await gateway.chat(for: key).load()
            await gateway.chat(for: key).refreshBranches()
        }
        try #require(gateway.chat(for: singleKey).hasLoaded && gateway.chat(for: singleKey).branches.count == 1)
        try #require(gateway.chat(for: branchedKey).hasLoaded && gateway.chat(for: branchedKey).branchHeaderChip != nil)
        try #require(gateway.subagentTree(rootKey: singleKey).runningCount == 0)
        try #require(gateway.subagentTree(rootKey: branchedKey).runningCount == 0)
        try #require(gateway.subagentTree(rootKey: runningKey).runningCount > 0)

        let emptyKey = try #require(await gateway.createSession(agentId: "main", label: "Empty toolbar control", select: false))
        let emptyListed = await eventually(timeout: .seconds(15)) { gateway.sessions[emptyKey] != nil }
        try #require(emptyListed)
        await gateway.chat(for: emptyKey).load()
        await gateway.chat(for: emptyKey).refreshBranches()
        try #require(gateway.chat(for: emptyKey).hasLoaded && gateway.chat(for: emptyKey).branches.isEmpty)
        let empty = try await self.measure(app, gateway: gateway, key: emptyKey)
        #expect(empty.itemCount == 1 && empty.visibleActionCount == 1 && empty.blankReservedFrames.isEmpty,
                "A zero-branch chat paints only compact overflow, with no reserved hidden controls")
        gateway.selectedKey = singleKey
        let transitionHost = NativeHost(app: app, gateway: gateway)
        defer { transitionHost.close() }
        let single = try await self.measure(app, gateway: gateway, key: singleKey, existingHost: transitionHost)
        let branched = try await self.measure(app, gateway: gateway, key: branchedKey, existingHost: transitionHost)
        let running = try await self.measure(app, gateway: gateway, key: runningKey, existingHost: transitionHost)
        let after = try await self.measure(app, gateway: gateway, key: singleKey, existingHost: transitionHost)
        for geometry in [single, branched, running, after] {
            #expect(geometry.itemCount == 1 && geometry.visibleActionCount == 1)
            #expect(geometry.blankReservedFrames.isEmpty,
                    "Model, Branch and Runs in overflow do not retain hidden native toolbar slots")
            #expect(abs(geometry.trailingGroupWidth - single.trailingGroupWidth) <= 1,
                    "Actual compact side width remains stable across Branch/Runs availability and chat switches")
        }
    }
}

@MainActor
extension TranscriptUIKitHostedTests {
    @Test(.timeLimit(.minutes(2)))
    func compactChatChromeOmitsBlankBranchSlots() async throws {
        try await CompactChatChromeToolbarTests().actualCompactNavigationBarReservesOnlyVisibleChatActions()
    }
}
#endif
